main: br.alkazuz.terrenos.Main
name: Terrenos
version: 1.1
description: Plugin de terrenos
softdepend:
  - WorldEdit
  - WorldGuard
  - Vault
  - ProtocolLib
commands:
  convertworldguard:
    description: Converte os terrenos do WorldGuard para o plugin
  terreno:
    description: Todos os comandos do plugin